name: zmab
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  
  # UI & Responsive
  flutter_screenutil: ^5.9.3
  responsive_framework: ^1.4.0
  
  # Images
  image_picker: ^1.1.2
  
  # Sharing
  share_plus: ^9.0.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Device Info
  device_info_plus: ^10.1.0
  
  # Utils
  uuid: ^4.4.0
  intl: ^0.20.2
  
  # Logger
  logger: ^2.3.0
  
  # Network
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Hive code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  
  # ... dependencias existentes
  pdf: ^3.10.8
  open_file: ^3.3.2 

flutter:
  uses-material-design: true
  generate: true
